spring:
  datasource:
    url: jdbc:mysql:///pharmacydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
store:
    storeNo: 400
    storeName: Apollo pharmacy
    storeManager: Anwesh
    openHours: 08
    openMinues: 30
    closingHours: 11
    closingMinutes: 00
    location: "Rourkela, Odisha"